config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    get 'statistics', on: :collection
    get 'actions', on: :collection
    get 'urgent_informations', on: :collection
    get 'repairs', on: :collection
    get 'search_by_model', on: :collection
    get 'before_destroy', on: :collection
    get 'add_trip', on: :collection
    resources :journeys 
    resources :car_options
    resources :repairs
  end

  devise_for :users

  delete 'users/sign_out', to: 'devise/sessions#destroy'

  devise_scope :user do
    root to: "devise/sessions#new"
  end 

  resources :users do
    resources :car_histories
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/user' => "cars#index", :as => :user_root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/views/shared/_navbar.html.erb
  <div id="navbar">
    <div class="navbar-part">
      <div class="primary-icon" style="margin-right: 1em"><%= link_to image_tag("logo-typo-white.svg"), cars_path %> </div>
      <% if current_user.cars.any? %>
        <div class="navbar-icon" title="Collection"><%= link_to image_tag("icon-cars4.svg"), cars_path %></div>
        <div class="navbar-icon"><%= link_to image_tag("icon-statistics!.svg"), statistics_cars_path %> </div>
        <div class="navbar-icon"><%= link_to image_tag("icon-actions!.svg"), actions_cars_path %> </div>
        <div class="navbar-icon"><%= link_to image_tag("icon-repair!.svg"), repairs_cars_path %> </div>
        <% if current_user.car_history %>
          <div class="navbar-icon"><%= link_to image_tag("icon-archives!!.svg"), user_car_history_path(current_user, current_user.car_history.id) %></div>
        <% end %>
          <div class="navbar-icon-notification">
            <%= link_to image_tag("icon-warnings-content.svg"), urgent_informations_cars_path %> 
              <% if @user_notification != 0 %>
                <div class="notification-chip">
                  <%=link_to(urgent_informations_cars_path, style: "text-decoration: none") do %>
                    <%= @user_notification %> <!-- Replace with the actual count of notifications -->
                  <% end %>
                </div>
              <% end %>
          </div>
      <% else %>
        <div class="navbar-icon"><%= link_to image_tag("icon-add-white.svg"), new_car_path %></div>
      <% end %>
    </div>
    <div class="navbar-part">
      <div class="navbar-icon">
        <%= link_to image_tag("icon-user!.svg"), edit_user_registration_path %> 
      </div>
      <div class="navbar-icon">
        <%= link_to image_tag("icon-sign-out!.svg"), users_sign_out_path %>
      </div> 
    </div>
  </div>