config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    get 'statistics', on: :collection
    get 'actions', on: :collection
    get 'urgent_informations', on: :collection
    get 'repairs', on: :collection
    get 'search_by_model', on: :collection
    get 'before_destroy', on: :collection
    get 'add_trip', on: :collection
    resources :journeys 
    resources :car_options
    resources :repairs
  end

  devise_for :users

  delete 'users/sign_out', to: 'devise/sessions#destroy'

  devise_scope :user do
    root to: "devise/sessions#new"
  end 

  resources :users do
    resources :car_histories
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/user' => "cars#index", :as => :user_root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :user
    has_one_attached :photo

    # TABLES ASSOCIATIONS

    has_one :maintainance, dependent: :destroy
    has_one :insurance, dependent: :destroy
    has_one :technical_control, dependent: :destroy
    has_one :car_option, dependent: :destroy
    has_many :repairs, dependent: :destroy
    has_many :journeys, dependent: :destroy

    accepts_nested_attributes_for :maintainance, allow_destroy: true
    accepts_nested_attributes_for :insurance, allow_destroy: true
    accepts_nested_attributes_for :technical_control, allow_destroy: true
    accepts_nested_attributes_for :car_option, allow_destroy: true
    accepts_nested_attributes_for :repairs, allow_destroy: true

    # VALIDATIONS

    # validates :model_year, presence: true, numericality: { only_integer: true }
    # validates :release_date, presence: true
    # validates :fuel, presence: true
    # validates :vehicle_type, presence: true
    # validates :fiscal_power, presence: true, numericality: { only_integer: true }
    # validates :required_licence, presence: true    
    # validates :horse_power, presence: true, numericality: { only_integer: true }
    # validates :seats, presence: true, numericality: { only_integer: true }
    # validates :acquisition_date, presence: true
    # validates :owners_number, presence: true, numericality: { only_integer: true }
    # validates :mileage, presence: true, numericality: { only_integer: true }
    # validates :to_sell, inclusion: { in: [true, false] }
    # validates :last_time_driven, presence: true
    # validates :model_specific_name, presence: true
    # validates :purchase_price, presence: true
    # validates :brand, presence: true
    # validates :numberplate, presence: true

    VEHICLE_TYPE_OPTIONS = ["Break", "SUV", "Truck", "Convertible", "Van", "Coupe", "Wagon", "Hatchback", "Spyder", "Other"].freeze
    FUEL_OPTIONS = ["Gasoline", "Diesel", "Electric", "Hybrid", "Other"].freeze
    INTERIOR_OPTIONS = ["Leather", "Velvet", "Wood", "Alcantara", "Silk", "Cashmere", "Wool"].freeze
    EXTERIOR_OPTIONS = ["Carbon", "Aluminium", "Titanium", "Kevlar", "Fiberglass", "Plastic", "Stainless Steel", "Chrome"].freeze
    CAR_CONDITION_STATES = ["Bad", "Average", "Good", "Excellent"].freeze
    INSURANCE_OPTIONS= ["Tout-risque", "Collection", "Au tiers", "Vol et dégradations"].freeze
    TIRE_STATES = ["Excellent", "Good", "Average", "Bad", "Worn out"].freeze
    GEARBOX_OPTIONS = ["Automatic", "Manual", "Semi-automatic", "Sequential", "Tiptronic", "Electric", "Other"].freeze
    MOTRICITY_OPTIONS = [
        "Front Traction",
        "Rear Traction",
        "Four-Wheel Traction (4x4)",
        "Selectable Traction"
      ]
    BRAND_OPTIONS = [
        "Abarth",
        "Alfa Romeo",
        "Aston Martin",
        "Audi",
        "Bentley",
        "BMW",
        "Bugatti",
        "Cadillac",
        "Chevrolet",
        "Chrysler",
        "Citroën",
        "Dacia",
        "Daewoo",
        "Daihatsu",
        "Dodge",
        "Donkervoort",
        "DS",
        "Ferrari",
        "Fiat",
        "Fisker",
        "Ford",
        "Honda",
        "Hummer",
        "Hyundai",
        "Infiniti",
        "Iveco",
        "Jaguar",
        "Jeep",
        "Kia",
        "KTM",
        "Lada",
        "Lamborghini",
        "Lancia",
        "Land Rover",
        "Landwind",
        "Lexus",
        "Lotus",
        "Maserati",
        "Maybach",
        "Mazda",
        "McLaren",
        "Mercedes-Benz",
        "MG",
        "Mini",
        "Mitsubishi",
        "Morgan",
        "Nissan",
        "Opel",
        "Peugeot",
        "Porsche",
        "Renault",
        "Rolls-Royce",
        "Rover",
        "Saab",
        "Seat",
        "Skoda",
        "Smart",
        "SsangYong",
        "Subaru",
        "Suzuki",
        "Tesla",
        "Toyota",
        "Volkswagen",
        "Volvo",
        "n/a"
    ].freeze
    LICENCE_OPTIONS = ["Permis Auto - B", "Permis Poids Lourd - C", "Permis Bus - D", "Permis Cyclomoteur - AM", "Permis Moto - A"].freeze
end

app/controllers/cars_controller.rb
require 'date'
require 'cloudinary'

class CarsController < ApplicationController
  before_action :set_user
  before_action :set_car, only: [:update, :destroy, :edit, :delete, :show]
  before_action :set_cars, only: [:index, :statistics, :urgent_informations, :repairs, :actions]

  def new
    @car = Car.new
    @car.build_car_option
    @car.build_insurance
    @car.build_maintainance
    @car.build_technical_control
  end

  def create
    @car = Car.new(car_params)
    @car.user_id = @user.id

    ActiveRecord::Base.transaction do
      if @car.save
        redirect_to cars_path, notice: 'Car has been created.', class: 'scale-in-ver-center'
      else
        render :new, notice: "Error. Car could not be created."
      end
    end
  end

  def update
    ActiveRecord::Base.transaction do
      if @car.update(car_params)
        redirect_to cars_path, notice: "Car's informations were successfully updated."
      else
        render :edit
      end
    end
  end
  
  def edit
    @car.car_option
    @car.insurance
    @car.maintainance
    @car.technical_control 
  end

  def destroy    
    selling_price = params[:car][:selling_price]

    car_history = @user.car_history
  
    if car_history.nil?
      CarHistory.create(
        user: current_user,
        total_sold_cars_value: selling_price,
        cars_sold: 1
      )
    else
      car_history.update(
        total_sold_cars_value: (car_history.total_sold_cars_value || 0) + selling_price.to_i,
        cars_sold: (car_history.cars_sold || 0) + 1
      )
    end

    @user.car.destroy
    redirect_to cars_url, notice: 'Car was successfully deleted, find the history of your cars in the dedicated window'
  end

  def add_trip 
    @user.car = Car.find(params[:format])
  end

  def before_destroy
    @user.car = Car.find(params[:format]) 
  end
  
  def index
    if params[:query].present? && @user.cars.present?
      @cars = search_by_model(params[:query])
      @reset_button = true
    else
      @cars = Car.where(user_id: @user.id)
      @reset_button = false
    end
  end

  def urgent_informations
    @unmaintained_cars = fetch_unmaintained_cars(@user.cars)
    @invalid_cars = fetch_invalid_cars(@user.cars)
    @uninsured_cars = fetch_uninsured_cars(@user.cars)
  end

  def show
    @insurance = @car.insurance 
    @maintainance = @car.maintainance
    @technical_control = @car.technical_control
    @repairs = @car.repairs if @car.repairs
    @valid_technical_control = @car.technical_control.valid_until > Date.today
    @valid_insurance = @car.insurance.assured_until > Date.today
    @interior_materials = JSON.parse(@car.car_option.interior_material)
    @exterior_materials = JSON.parse(@car.car_option.exterior_material)
    @health_score = 80
    # @journeys_by_cars = fetch_journeys_by_cars(@cars)
    # HEALTH SCORE FUNCTION
  end

  def statistics
    @yearly_date = Date.today.year
    @total_cars_worth = calculate_total_cars_worth(@user.cars)
    @cars_number = @user.cars.count
    @total_cars_worth_string = separate_number_with_dots(@total_cars_worth)
    @average_car_mileage = average_car_mileage(@user.cars)
    @average_car_age = average_car_age(@user.cars)
    @total_insurance_costs = calculate_total_insurance_cost(@user.cars)
  end

  def actions 
    # setup warnings for technical control
    # setup insurance reminder 
    # setup maintainance control with a periodicity
  end

  private

  def set_user 
    @user = current_user
  end

  def search_by_model(query)
    query = query.downcase
    cars = Car.where(user_id: @user.id)
  
    return if cars.empty?

    model_names_with_ids = cars.pluck(:model_specific_name, :id).to_h
    brands_with_ids = cars.pluck(:brand, :id).to_h
  
    model_names_with_ids.transform_keys!(&:downcase)
    brands_with_ids.transform_keys!(&:downcase)
  
    model_results = model_names_with_ids.select { |model_name, _id| model_name.include?(query) }
    matched_ids = model_results.values
  
    brand_results = brands_with_ids.select { |brand, _id| brand.include?(query) }
    matched_ids.concat(brand_results.values.flatten) unless brand_results.empty?

    return query = nil if matched_ids.empty?
  
    matched_cars = Car.where(id: matched_ids)
    matched_cars.empty? ? nil : matched_cars
  end
  

  def fetch_journeys_by_cars(cars)
    global_hash = {}

    cars.each do |car|
      next unless car.journeys.any?
    
      car_journeys = { car.id => { car: car, journeys: Journey.where(car_id: car.id).pluck(:id) } }
      global_hash.merge!(car_journeys)
    end

    data_for_chart = global_hash.map do |car_id, car_data|
      {
        name: car_data[:car].model_specific_name,
        data: { "Car #{car_id}" => car_data[:journeys].count }
      }
    end

    return data_for_chart
  end


  def fetch_invalid_cars(cars)
    return unless cars

      cars.select do |car|
        car.technical_control.valid_until <= Date.today
      end
  end

  def fetch_unmaintained_cars(cars)
    return unless cars
  
    selected_cars = cars.select do |car|
      car.maintainance.last_repair_date.year <= Date.today.year - 3 || 
      car.maintainance.maintainance_needed 
    end
  end

  def fetch_uninsured_cars(cars)
    return unless cars

    cars.select do |car|
      car.insurance.assured_until < Date.current
    end
  end

  def calculate_total_insurance_cost(cars)
    return unless cars
  
    total_costs = cars.sum { |car| car.insurance.assurance_price }
  
    separate_number_with_dots(total_costs)
  end

  def average_car_mileage(cars)
    return unless cars && cars.any?
  
    total_mileage = cars.sum(&:mileage)
    average_car_milage = total_mileage / cars.size if total_mileage.positive?
  
    separate_number_with_dots(average_car_milage)
  end
  
  def average_car_age(cars)
    return "No data" unless cars && cars.any?
  
    current_year = Date.today.year
    total_cars_age = cars.sum { |car| current_year - car.model_year }
  
    counter = cars.count
    average_age = (counter > 0) ? (total_cars_age / counter) : 0
  end

  def set_car 
    @car = Car.find(params[:id])
  end 

  def calculate_total_cars_worth(cars)
    if cars 
      total_cars_worth = 0
      cars.each do |car|
        total_cars_worth += car.purchase_price.to_i
      end
      return total_cars_worth
    end
  end

  def set_cars
    @cars = Car.all
  end

  def separate_number_with_dots(number)
    total_value_string = ""

    return total_value_string = number.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1 ').reverse
  end

  def car_params
    params.require(:car).permit(
      :model_specific_name, :model_year,:release_date, :brand, :fuel, :motricity, 
      :gearbox, :vehicle_type, :model, :door_number, :fiscal_power,
      :required_licence, :horse_power, :seats, :acquisition_date, 
      :owners_number, :tire_size_front, :tire_size_back, :mileage, 
      :purchase_price, :estimated_value, :geolocalisation, :drivable, :accidented, :to_sell, :last_time_driven, 
      :numberplate, :required_licence, :interior_state, :exterior_state, :acquisition_date, :photo, 
      :drive_count_since_acquisition, :journey_taken, :regularly_maintained, :tires_state, :selling_price,

      car_option_attributes: [
        :exterior_color, :interior_color, :motricity, :gearbox, :vehicle_type,
        :model, :door_number, :specifications, interior_material: [], exterior_material: [], 
      ],

      insurance_attributes: [
        :assurance_type, :assured_until, :assurance_price,
        :assurance_company
      ],

      maintainance_attributes: [
        :maintainance_costs, :maintainance_needed, :drivable, :accidented,
        :repair_company, :last_repair_date
      ],

      technical_control_attributes: [
        :technical_control_frequency, :technical_control_price, :control_company,
        :counter_visit_at_last_control, :issues_encountered, :valid_until
      ])
  end

  def insurance_params
    params.require(:car).permit(:insurance_attributes).permit(
      :assurance_type, :assured_until, :assurance_price, :assurance_company
    )
  end

  def maintainance_params
    params.require(:car).permit(:maintainance_attributes).permit(
      :maintainance_costs, :maintainance_needed, :drivable, :accidented,
      :major_issues, :maintainance_periodicity, :repair_company, :last_repair_date
    )
  end

  def technical_control_params
    params.require(:car).permit(:technical_control_attributes).permit(
      :technical_control_frequency, :technical_control_price, :control_company,
      :counter_visit_at_last_control, :issues_encountered, :valid_until
    )
  end

  def car_option_params
    params.require(:car).permit(:car_option_attributes).permit(
      :exterior_color, :interior_color, :motricity, :gearbox, :vehicle_type,
      :model, :door_number, :modifications, :modified, :original, :specifications,
      :leather_interior, interior_material: [], exterior_material: []
    )
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/actions.html.erb
<div class="global-secondary-container">
    <h1> Actions to set up </h1>
</div>

app/views/cars/add_trip.html.erb
<div class="modal">
    <div class="secondary-container" style="margin-top: -1.6em; margin-bottom: 0.6em;">
    <div style= "display: flex; justify-content: start; align-items: center; width: 100%; margin-top: 1em; margin-bottom: 1.4em;">
                <div><%= link_to "Back to car", :back, class: "primary-button"%></div>
            </div>
            <%= form_with(model: Journey.new, url: car_journeys_path(car_id: @car.id), method: :post) do |f| %>
            <div class="primary-centered">
            <h3> Add a trip to your <%= @car.model_specific_name %></h3>
                <div class="primary-centered">
                    <p> When did you last go on a trip ? </p>
                    <div><%= f.date_field :date, as: :string, input_html: { data: { controller: "datepicker" } }, required: true %></div>
                </div>
                <div class="primary-centered">
                    <p><%= f.label :mileage, "How long was the trip ? (km)" %></p>
                    <%= f.number_field :mileage, placeholder: 80%>
                </div>
                    <%= f.submit "Add a trip", style: "text-decoration:none; color:white; border-radius: .25rem !important; margin-top: 2em;", class: "thirdary-button" %>
            </div>
            <% end %>
    </div>
</div>

app/views/cars/before_destroy.html.erb
    <div class="modal">
            <div class="secondary-container">
            <div style= "display: flex; justify-content: start; align-items: center; width: 100%; margin-top: -2em; margin-bottom: 1.4em;">
                <div><%= link_to "Back to car", :back, class: "primary-button"%></div>
            </div>
                <%= form_with(model: @car, url: car_path(@car), method: :delete) do |f| %>
                    <div class="primary-centered">
                        <div class="field">
                        <p><%= f.label :selling_price, "Did you sell the car ? If yes, please write its selling price :" %></p>
                        </div>
                        <div class="field">
                        <%= f.number_field :selling_price, placeholder: 15000, required: true %>
                        </div>
                        <div class="primary-centered"><%= f.submit "Delete from collection", style: "text-decoration:none; border-radius: 0.25rem !important; margin-top: 2em;", class:"thirdary-button"%></div>
                <% end %>
    </div>     
</div>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/index.html.erb
<div class="cargo-container">
  <div class="top-content-container">
    <div class="input-container">
      <%= form_with(url: cars_path, method: :get, html: { id: 'search-form' }) do |f| %>
        <%= f.text_field :query, placeholder: "Search by model or brand...", id:"search-model-input" %>
          <span class="clear-icon" 
          onclick="
          document.getElementById('search-model-input').value = '';
          window.location.reload();
          "
          >&#10006;</span>          
          <%= f.submit 'Search', id: 'search-submit', style: 'display: none;' %>
          <label for="search-submit" class="search-icon">&#128269;</label>
        <% end %>
    </div>
    <div class="thirdary-button"><%= link_to "Add a car", new_car_path, style: "text-decoration:none; color:white;"%></div>
  </div>
</div>

<% if @cars.present? %>
  <div class="title-with-image">
      <%= image_tag('icon-cars4', class:'car-chart-icon')%>
      <h3> Your collection </h3>
  </div>
<% elsif params[:query].present?  %>
  <div class="global-primary-container">
    <p>No data has been found.</p>
  </div>
  <% else %>
  <div class="primary-centered" style="margin-bottom: 2em;">
    <p>No car has been added yet.</p>
    <div class="thirdary-button"><%= link_to"Add a car", new_car_path, style:"text-decoration: none; color:white" %> </div>
  </div>
<% end %>

<% if @cars.present? %>
  <div class="global-primary-container" style= "margin-bottom: 10em; margin-top: 0;">
      <p><i>
          <%= @cars.present? ? "#{@cars.count} car(s)" : "No data found" %>
      </p></i>
    <div class="index-car-grid-container">

      <% @user.cars.each do |car| %>

        <div class="index-car-card">
        <%= cl_image_tag(car.photo.key, class: "car-index-image") %>

          <div class="bottom-index-card-content">

            <h3> <%= car.brand %> <%= car.model_specific_name %> </h3> 

            <div class="align-items">
              <p> Technical inspection : </p>
                <% if car.technical_control.valid_until >= Date.today %>
                    <%= image_tag("icon-valid", class: "small-icon")%> 
                    <% else %>
                    <%= image_tag("icon-invalid", class: "small-icon") %>
                <% end %> 
              </div>

              <div class="align-items">
                <p> Insurance : </p>
                <% if car.insurance.assured_until >= Date.today %>
                    <%= image_tag("icon-valid", class: "small-icon")%> 
                    <% else %>
                    <%= image_tag("icon-invalid", class: "small-icon") %>
                <% end %> 
              </div>

               <div class="align-items" style= "margin-bottom: 2em">
                <p> Maintainance needed : </p>
                <% if car.maintainance.maintainance_needed %>
                    <p style="color: red"><strong>Yes</strong></p>
                    <% else %>
                    <p>No</p>
                <% end %> 
              </div>

            <p>Last maintainance : <%= car.maintainance.last_repair_date.year %></p>
            
            <div class="icon-container">
                <div class="button-container">
                    <%= link_to image_tag("icon-go-to-white.svg"), car_url(car), class: "small-icon" %>
                </div>
            </div>

          </div>

        </div>
      <% end %>
    <% end %>
  </div>
    <div class="primary-centered" style="margin-top:2em;">
      <% if @reset_button %>
        <div class="thirdary-button"> <%= link_to "Reset", cars_path, style:"text-decoration: none; color:white;" %></div>
      <% end %>
    </div>
</div>

app/views/cars/repairs.html.erb
<div class="global-secondary-container">
    <h1> Repairs </h1>
    <div class="">
       
    </div>
</div>

app/views/cars/statistics.html.erb
<div class="global-secondary-container" style="margin-bottom:6em">
    <h1> Statistics </h1>
    <div class="width-container">

        <div class="title-with-image">
            <%= image_tag("icon-statistics!.svg", class:"car-chart-icon") %>
            <h1>Global statistics</h1>
         </div>

        <div class="grid-statistics-container">
        
            <div class="grid-card">
            <% if @total_cars_worth > 0 %>
                <div class="grid-card-content">
                <p> Total current value : <h4 class="statistics"> <%= @total_cars_worth_string %> € </h4></p>
                <% end %>
                </div>
            </div>

            <div class="grid-card">
            <% if @cars_number > 0 %>
                <div class="grid-card-content">
                <p> Number of cars : <h4 class="statistics"> <%= @cars_number %> </h4></p>
                </div>
                <% end %>
            </div>

            <div class="grid-card">
                <div class="grid-card-content">
                    <p > Average car mileage : <h4 class="statistics"> <%= @average_car_mileage %> km </h4></p>
                </div>
            </div>
            
            <div class="grid-card">
                <div class="grid-card-content">
                    <p>Average car age:
                        <h4 class="statistics">
                            <%= @average_car_age.present? ? "#{@average_car_age} year(s)" : "No data" %>
                        </h4>
                    </p>
                </div>
            </div>

            <div class="grid-card">
                <div class="grid-card-content">
                    <p>Car(s) to sell :
                    <h4 class="statistics">
                        <%= @cars.present? ? Car.where(to_sell: true).count : "No cars to sell" %>
                    </h4>
                    </p>
                </div>
            </div>

            <div class="grid-card">
                <div class="grid-card-content">
                    <p> Total costs of insurance for <%= @yearly_date %> : 
                    <h4 class="statistics"> <%= @total_insurance_costs %> € </h4>
                    </p>
                </div>
            </div>
        </div>

        <div class="title-with-image">
            <%= image_tag("icon-charts!.svg", class:"car-chart-icon") %>
            <h1>Charts</h1>
         </div>

           <% if Journey.any? %>
            <div class="chart-cake">
                <div class="chart-half">
                        <h3>Trip Frequency</h3>
                        <%= line_chart Journey.all.group_by_week(:date).count, label: "Trip frequency" %>
                </div>

                <div class="chart-half">
                    <h3>Cars by brand</h3>
                    <%= bar_chart @cars.group(:brand).count, donut: true, label: 'Brand' %>
                </div>
            </div>
            <%else%>
            <div class="secondary-container">
                <p> Not enough data available. Add some more cars to discover statistics. </p>
            </div>
        <% end %>
    </div>
</div>
</div>

app/views/cars/urgent_informations.html.erb
<div class="global-primary-container">
    <h1> Urgent informations </h1>
    <div class="table-grid">
        <div class="table-container">
           <div class="flex-start">
                <%= image_tag("icon-engine.svg", class:"primary-illustration") %>
                <h3>Maintainance</h3>
            </div>
        <p> Cars which have not been maintained since 3 years at least and cars that you want to maintain as soon as possible : </p>
        <% if @unmaintained_cars.present? %>
        <div class="flex-start-warning">
                <div class="secondary-icon"> <%= image_tag("icon-warnings-content.svg") %> </div>
                <p><%= @unmaintained_cars.count %> car(s) need(s) a maintainance.</p>
        </div>
            <table>
                <thead>
                    <tr>
                    <th>Model</th>
                    <th class="align-items">Last Maintenance Date </th>
                    </tr>
                </thead>
                    <tbody>
                        <% @unmaintained_cars.each_with_index do |car, index| %>
                            <tr class="<%= index.odd? ? 'row-odd' : 'row-even' %>">
                                <td><%= car.model_specific_name %></td>
                                <td><%= car.maintainance.last_repair_date %></td>
                                <td class="icon-cell">
                                <div class="primary-button">
                                    <%= link_to "Show", car_path(car.id), style: "text-decoration: none; color: black;"%>
                                </div>
                                </td>
                                <td class="icon-cell">
                                <div class="primary-button">
                                    <%= link_to "Edit", edit_car_path(car.id), style: "text-decoration: none; color: black;" %>
                                </div>
                                </td>
                            </tr>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            <div class="primary-centered">
                <%= image_tag('icon-valid', class:'small-icon') %>
                <p>No cars need a maintainance.</p>
            </div>
        <% end %>
        </div>

    <div class="table-container">
        <div class="flex-start">
                <%= image_tag("icon-repair.svg", class:"primary-illustration") %>
                <h3>Technical inspection </h3>
            </div>
        <p> Cars with invalid technical inspections : </p>
        <% if @invalid_cars.present? %>
           <div class="flex-start-warning">
                <div class="secondary-icon"> <%= image_tag("icon-warnings-content.svg") %> </div>
                <% if @invalid_cars.count == 1 %>
                    <p><%= @invalid_cars.count %> car has no valid inspection.</p>
                    <% else %>
                    <p><%= @invalid_cars.count %> cars don't have a valid inspection.</p>
                <% end %>
            </div>
                <table>
                    <thead>
                        <tr>
                        <th>Model</th>
                        <th class="align-items">Invalid since </div></th>
                        </tr>
                    </thead>
                        <tbody>
                        <% @invalid_cars.each_with_index do |car, index| %>
                        <tr class="<%= index.odd? ? 'row-odd' : 'row-even' %>">
                            <td><%= car.model_specific_name %></td>
                            <td><%= car.maintainance.last_repair_date %></td>
                            <td class="icon-cell">
                            <div class="primary-button">
                                <%= link_to "Show", car_path(car.id), style: "text-decoration: none; color: black;"%>
                            </div>
                            </td>
                            <td class="icon-cell">
                            <div class="primary-button">
                                <%= link_to "Edit", edit_car_path(car.id), style: "text-decoration: none; color: black;" %>
                            </div>
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                <% else %>
                <div class="primary-centered">
                    <%= image_tag('icon-valid', class:'small-icon') %>
                    <p>No cars need technical inspection.</p>
                </div>
            <% end %>
        </div>

  <div class="table-container">
        <div class="flex-start">
                <%= image_tag("icon-administrative.svg", class:"primary-illustration") %>
                <h3>Insurance </h3>
            </div>
        <p> Cars with invalid technical inspections : </p>
        <% if @uninsured_cars.present? %>
           <div class="flex-start-warning">
                <div class="secondary-icon"> <%= image_tag("icon-warnings-content.svg") %> </div>
                <% if @uninsured_cars.count == 1 %>
                    <p><%= @uninsured_cars.count %> car is not insured.</p>
                    <% else %>
                    <p><%= @uninsured_cars.count %> cars are not insured.</p>
                <% end %>
            </div>
                <table>
                    <thead>
                        <tr>
                        <th>Model</th>
                        <th class="align-items">Invalid since </div></th>
                        </tr>
                    </thead>
                        <tbody>
                        <% @uninsured_cars.each_with_index do |car, index| %>
                        <tr class="<%= index.odd? ? 'row-odd' : 'row-even' %>">
                            <td><%= car.model_specific_name %></td>
                            <td><%= car.maintainance.last_repair_date %></td>
                            <td class="icon-cell">
                            <div class="primary-button">
                                <%= link_to "Show", car_path(car.id), style: "text-decoration: none; color: black;"%>
                            </div>
                            </td>
                            <td class="icon-cell">
                            <div class="primary-button">
                                <%= link_to "Edit", edit_car_path(car.id), style: "text-decoration: none; color: black;" %>
                            </div>
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                 <% else %>
                <div class="primary-centered">
                    <%= image_tag('icon-valid', class:'small-icon') %>
                    <p>No cars need to be insured.</p>
                </div>
            <% end %>
        </div>
</div>